"""Add server-side UUID generation for primary keys

Revision ID: 431c74051b34
Revises: 47bf243a8d28
Create Date: 2025-07-12 16:51:54.929208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431c74051b34'
down_revision: Union[str, None] = '47bf243a8d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
